#!/bin/bash
function dumpdb() {
  DB_USER=$( grep DB_USER wp-config.php | cut -d "'" -f 4)    
  DB_PASS=$( grep DB_PASSWORD wp-config.php | cut -d "'" -f 4)
  DB_NAME=$( grep DB_NAME wp-config.php | cut -d "'" -f 4)
  DB_HOST=$( grep DB_HOST wp-config.php | cut -d "'" -f 4)
    if [[ $DB_HOST == *':'* ]]; then 
      DB_HOST=$( grep DB_HOST wp-config.php | cut -d "'" -f 4 | cut -d ':' -f 1)
      PORT=$( grep DB_HOST wp-config.php | cut -d "'" -f 4 | cut -d ':' -f 2)
      mysqldump -u "$DB_USER"  -p"$DB_PASS" "$DB_NAME" -h "$DB_HOST" --port="$PORT" > "$DB_NAME".sql
    else 
      mysqldump -u "$DB_USER"  -p"$DB_PASS" "$DB_NAME" -h "$DB_HOST" > "$DB_NAME".sql
    fi
  if test -f "$DB_NAME".sql ; then
    echo "Successfully dumped DB $DB_NAME"
  else
    echo "Did not dump DB $DB_NAME"
  fi
}
dumpdb
