#!/bin/bash
function findwpandimport() {
    find ~/public_html -type f -name wp-config.php | sed 's/wp-config.php//' | while read x; do
        cd $x
        matchdbimport
    done
}
findwpandimport
