#!/bin/bash

function help() {
	echo -e '

Prompts for a list of urls to WordPress backup files and installs the site in the current directory.

example usage:
$ free_wordpress --wp-version="5.3.3" --php-version="7.3"

options:
-h --help : displays this message
-t --test : runs automated testing on the functions in this file.
-w --wordpress-version : sets the wordpress version of the install
-p --php-version : sets the php version of the install
'
	exit 0
}

function downloadSignedLinks() {
	echo 'Paste in backup file urls 1 per line. Press ctrl d when done.'
	links=$(cat)
	for x in $links
	do
		echo -e "
downloading $x
"
		filename=$(echo $x | grep -oP \(mu-p\)\?[a-z]+\.zip)
		wget -t3 $x -O $filename
		if [ $? != 0 ]; then
			echo "could not download $x"; exit 1
		fi
	done
	echo 'All backup files have been successfully downloaded'
}

function download_wordpress() {
	tarname=$1
			echo -e "
downloading $tarname
"
	wget -t3 https://wordpress.org/$tarname > /dev/null
	expectedhash=$(curl -s https://wordpress.org/$tarname.md5)
	filehash=$(md5sum $tarname 2>/dev/null | cut -d ' ' -f1)
	if [[ "$filehash" == "$expectedhash" ]]; then
		# tar -xf --strip-components 1 $tarname  # doesnt work on mac
		tar -xf $tarname
		mv wordpress/* .
		rmdir wordpress
		rm $tarname 2>/dev/null
		return 0
	else
		echo "the hash did not match"
		echo recieved $filehash
		echo expected $expectedhash
		rm $tarname 2>/dev/null
		exit 1
	fi
}

function safetyCheck() {
    if [[ $(pwd) != *"public_html"* ]]; then
		echo "Please run in public_html or deeper. Ideally an empty directory. You are in $(pwd)"; exit 1
	fi
	if [[ $(ls index.* 2>/dev/null) ]] || [[ $(ls wp-content 2>/dev/null) ]]; then
        echo 'There is already a site here'; exit 1
	fi
}
function extractZip() {
	unzip -o $1 -d $2
	if [ $? -ne 0 ]; then
		timestamp=$(date +%s)
		echo "there was trouble extracting ~/$timestamp-$1 to $2" >> ~/migration-error-log
		echo "failed operation was unzip -o $1 -d $2" >> ~/migration-error-log
	else
		rm $1
	fi
}

function extractZips() {
	for i in $(ls -1 *.zip)
do
echo running
case $i in
    plugins*)
	extractZip $i 'wp-content/plugins'
    ;;
    mu-plugins*)
	extractZip $i 'wp-content/mu-plugins'
    ;;
	uploads*)
	extractZip $i 'wp-content/uploads'
    ;;
	themes*)
	extractZip $i 'wp-content/themes'
    ;;
	db*)
	extractZip $i 'wp-content'
    ;;
	root**)
	extractZip $i '.'
    ;;
esac
done
}

function main() {
	safetyCheck
	if [ "$wp_version" == "" ]; then
		downloadSignedLinks
		download_wordpress latest.tar.gz
	else
		wp_version_check=$(echo $wp_version | grep -oP ^[456]\.\\d?\.?\\\d$)
		if [ "$wp_version_check" == "" ]; then
			echo "That WordPress version does not look right '$wp_version'"
			exit 1
		else
			downloadSignedLinks
			download_wordpress wordpress-$wp_version.tar.gz
		fi
	fi
	extractZips
	mv wp-config-sample.php wp-config.php
	wpdbimport wp-content/database.sql
	wp config set table_prefix design_
	cat ~/migration-error-log 2>/dev/null
}

function test() {
	# setup test env
	mkdir /tmp/public_html
	echo testing > /tmp/public_html/free-wordpress
	if [ $? -ne 0 ]; then
		echo tests cannot be ran on this environment. No access to /tmp
		exit 1
	fi
	rm -rf /tmp/public_html
	cd /tmp/

	# test that cannot install outside of public_html
	echo testing safetyCheck
	exited=$(safetyCheck)
	if [[ $(echo $exited | grep Please) ]]; then
		echo 'passed safetyCheck test 1'
	else
		>&2 echo "Safety check allowed install outsite of public_html"; exit 1
	fi

	# test that can install inside a clean public_html
	mkdir /tmp/public_html
	cd /tmp/public_html
	exited=$(safetyCheck)
	cd /tmp
	rmdir /tmp/public_html
	if [[ $(echo $exited | grep 'site here') ]]; then
		>&2 echo 'Safety check did not allow install under good conditions'; exit 1
	else
		echo 'passed safetyCheck test 2'
	fi

	# test that cannot install when there is a site
	mkdir /tmp/public_html
	cd /tmp/public_html
	touch index.php
	exited=$(safetyCheck)
	cd /tmp
	rm -rf /tmp/public_html
	if [[ $(echo $exited | grep 'site here') ]]; then
		echo 'passed safetyCheck test 3'
	else
		>&2 echo 'Safety check allowed install in a directory containing an index file'; exit 1
	fi


	# close out tests
	echo all tests passed
	exit 0
}

for i in "$@"
do
case $i in
    -w=*|--wp-version=*)
    wp_version="${i#*=}"
    ;;
    -p=*|--php-version=*)
    php_version="${i#*=}"
    ;;
	-h|--help)
    help
    ;;
	-t|--test)
    test
    ;;
esac
done

main