#!/bin/bash

# check to see if there's an argument

if [ -z "$1" ]; then
  echo -e 'USAGE: mailsync [domain]'
  exit 1
fi 

if [ ! -d ~/migration/migstuff/ ] ; then  
  mkdir -p ~/migration/migstuff/logs/"$1"/ 2>/dev/null
fi

echo ''
timestamp=$(date +%s)

# function to count inodes in mail dir for domain 

echo ' ' > ~/migration/migstuff/logs/"$1"/beforesync_"$1"_"$timestamp".txt
echo ' ' > ~/migration/migstuff/logs/"$1"/aftersync_"$1"_"$timestamp".txt

# function to format and send count to file 

function count_and_Format() {
  if [[ -d ~/mail/$1 ]]; then 
    find ~/mail/$1/ -printf "%h\n" | cut -d/ -f-2 | sort | uniq -c | sort -rn | sed -rn "s/\s*\.\/(.*+)/\t\1@$1/p"
  fi 
}

echo -e "Migrating mail for $1\n"

# record mail box state from before sync

echo -e 'PREVIOUS' 1> ~/migration/migstuff/logs/"$1"/beforesync_"$1"_"$timestamp".txt
count_and_Format $1 1>> ~/migration/migstuff/logs/"$1"/beforesync_"$1"_"$timestamp".txt 

# do the actual sync 

creds=$(cat ~/migration/migstuff/source.txt)

#check rsync version for progress option
rsync_version=$(rsync --version | grep -oP 'rsync\s+version\s\K(\d\.\d)' | sed -rn 's/\.//p')

rsync --dry-run -avP -e "ssh -i ~/migration/migstuff/id_rsa" $creds:~/mail/${1%/} ~/mail 1> ~/migration/migstuff/logs/"$1"/dryrun_mailsync_mail_log_"$timestamp".txt &

if [[ "$rsync_version" -lt "31" ]]; then 
  echo "Syncing mail, no progress bar available"
  # sync etc
  rsync --dry-run --ignore-existing -avP -e "ssh -i ~/migration/migstuff/id_rsa" $creds:~/etc/${1%/} ~/etc 1> ~/migration/migstuff/logs/"$1"/dryrun_mailsync_etc_log_"$timestamp".txt &
  rsync -h --ignore-existing -a --no-i-r -e "ssh -i ~/migration/migstuff/id_rsa" $creds:~/etc/${1%/} ~/etc | tee ~/migration/migstuff/logs/"$1"/mailsync_log_"$timestamp".txt
  #sync mail 
  rsync -h -a --no-i-r -e "ssh -i ~/migration/migstuff/id_rsa" $creds:~/mail/${1%/} ~/mail | tee -a ~/migration/migstuff/logs/"$1"/mailsync_log_"$timestamp".txt
else 
  # sync etc
  rsync --dry-run --ignore-existing -avP -e "ssh -i ~/migration/migstuff/id_rsa" $creds:~/etc/${1%/} ~/etc 1> ~/migration/migstuff/logs/"$1"/dryrun_mailsync_etc_log_"$timestamp".txt &
  rsync -h --ignore-existing -a --no-i-r --info=progress2 -e "ssh -i ~/migration/migstuff/id_rsa" $creds:~/etc/${1%/} ~/etc | tee ~/migration/migstuff/logs/"$1"/mailsync_log_"$timestamp".txt
  #sync mail 
  rsync -h -a --no-i-r --info=progress2 -e "ssh -i ~/migration/migstuff/id_rsa" $creds:~/mail/${1%/} ~/mail | tee -a ~/migration/migstuff/logs/"$1"/mailsync_log_"$timestamp".txt
fi

# count inodes of updated mail boxes

echo -e 'CURRENT' 1> ~/migration/migstuff/logs/"$1"/aftersync_"$1"_"$timestamp".txt
count_and_Format $1 1>> ~/migration/migstuff/logs/"$1"/aftersync_"$1"_"$timestamp".txt 

# final output, compare states 

diff -T -y --ignore-matching-lines=CUR ~/migration/migstuff/logs/"$1"/beforesync_"$1"_"$timestamp".txt ~/migration/migstuff/logs/"$1"/aftersync_"$1"_"$timestamp".txt 1> ~/migration/migstuff/logs/"$1"/"$1"_"$timestamp".txt 

sleep 1

echo ' '

cat ~/migration/migstuff/logs/"$1"/"$1"_"$timestamp".txt 

echo ' '
