#!/bin/bash
    if [[ $(echo $1) ]] && [[ $(echo $2) ]]; then
        sshline=$(head -n 1 ~/migration/migstuff/source.txt)
        ifile=$(ls ~/migration/migstuff/id_rsa)
        if [[ $(echo $ifile) ]]; then
            sourcessh="ssh -i $ifile $sshline"
            rsync -aPe "ssh -i $ifile" $sshline:$1 $2
        else
            echo please run setupssh first
        fi
    else
        echo we need 2 arguments
    fi
