#!/bin/bash
alias today='echo $(date +%s)'
function premig() {
  TODAY=$(date +%s)
  mkdir ~/premig.${TODAY}
  find ./ -maxdepth 1 \( -type f -name "*" -o -name "wp-admin" -o -name "wp-content" -o -name "wp-includes" -o -name "cgi-bin" -o -name ".well-known" \) -exec mv -t ~/premig.${TODAY} {} \;
  echo -e "\e[32mMoved all files, wp-admin, wp-includes, wp-content to ~/premig.${TODAY}."
  echo -e "Check if any remaining directories are for sub/addon domains.\e[0m]"
}
premig
