#!/bin/bash
    if [[ -f $3 ]]; then
    cp $3 ${3}.bkup
    echo 'sed -i "s,$1,$2,g" $3'
    sleep 2
    sed -i "s,$1,$2,g" $3
    echo
    echo "######################"
    echo
    echo "      File: $3"
    echo "      Old: $1"
    echo "      New: $2"
    echo
    echo "######################"
    else
    echo "error"
    echo "file $3 could not be found.."
    fi
