#!/bin/bash
function secureit() {
  GREEN='\033[0;32m'
  NC='\033[0m' #No Color
  if test -f ~/bin/migbin/bashrc ; then 
    if [[ -d ./.well-known ]]; then 
        newdir=$(echo ".old_well-known-$(date +%s)")
        mkdir $newdir
        mv .well-known "$newdir"/
    fi
    site_url=$(~/bin/migbin/wpurl | tail -n +2 | head -n 1 | awk '{print $3}' | sed -E 's/(.*https:\/\/)|(.*http:\/\/)//g' | sed -E 's/(.*www\.)//g' )
    home_url=$(~/bin/migbin/wpurl | tail -n 1 | awk '{print $3}' | sed -E 's/(.*https:\/\/)|(.*http:\/\/)//g' | sed -E 's/(.*www\.)//g' )
    secure_site=$(echo 'https://'"$site_url" )
    wwwsecure_site=$(echo 'https://www.'"$site_url" )
    secure_home=$(echo 'https://'"$home_url" )
    wwwsecure_home=$(echo 'https://www.'"$home_url" )
    insecure_site=$(echo 'http://'"$site_url")
    wwwinsecure_site=$(echo 'http://www.'"$site_url")
    insecure_home=$(echo 'http://'"$home_url")
    wwwinsecure_home=$(echo 'http://www.'"$home_url")
    ~/bin/migbin/wp search-replace "$insecure_site" "$secure_site" | tail -n 1 2> /dev/null
    ~/bin/migbin/wp search-replace "$wwwinsecure_site" "$wwwsecure_site" | tail -n 1 2> /dev/null
    ~/bin/migbin/wp search-replace "$insecure_home" "$secure_home" | tail -n 1 2> /dev/null
    ~/bin/migbin/wp search-replace "$wwwinsecure_home" "$wwwsecure_home" | tail -n 1 2> /dev/null
    ~/bin/migbin/wp cache flush
    wp plugin list --skip-themes --skip-plugins 2> /dev/null | tail -n +2 | grep -v inactive | grep -v must-use | grep -v dropin | awk '{print $1}' | while read active_plugin ; do
      if [[ "$active_plugin" == 'elementor' ]] ; then 
        echo 'Fixing Elementor URLs'
        ~/bin/migbin/wp elementor replace_urls "$insecure_site" "$secure_site" 2>/dev/null
        ~/bin/migbin/wp elementor replace_urls "$wwwinsecure_site" "$wwwsecure_site" 2>/dev/null
        ~/bin/migbin/wp elementor replace_urls "$insecure_home" "$secure_home" 2>/dev/null
        ~/bin/migbin/wp elementor replace_urls "$wwwinsecure_home" "$wwwsecure_home" 2>/dev/null
        ~/bin/migbin/wp elementor flush_css 2>/dev/null
      fi 
    done 
    wpht
    echo -e "SITE_URL = ${GREEN}$(wpurl | tail -n +2 | head -n 1 | awk '{print $3}' )" ${NC}
    echo -e "HOME_URL = ${GREEN}$(wpurl | tail -n 1 | awk '{print $3}' )" ${NC}
  fi
}
secureit
